- name: Frontend Setup
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Copy Expense Configuration
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: CLean old directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download and Extract App content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Start nginx
      ansible.builtin.systemd_service:
       state: restarted
       name: nginx
       enabled: yes

