- name: Get Secrets
  hosts: localhost
  tasks:
    - name: Create a file
      ansible.builtin.lineinfile:
        path: /tmp/test
        line: "Username: {{ lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.devopssz14.online:8200 validate_certs=False')}}"
        create: yes