- name: Get Secrets
  hosts: localhost
  tasks:

  - name: Create App Secrets file
    ansible.builtin.lineinfile:
     path: app.json
     line: "{{lookup('hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{vault_token}} url=https://vault.devopssz14.online:8200 validate_certs=False')}}"
     create: yes

- name: Create Common Secret
  ansible.builtin.shell: for i in $(ls ~/*.json); do echo -n $(cat $i) ;done | sed -e 's/}{/, /g' >~/secrets.json
       #  - name: Create a file
       # ansible.builtin.lineinfile:
       # path: /tmp/test
       #line: "Username: {{ lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.devopssz14.online:8200 validate_certs=False')}}"
      #create: yes