# - name: Install Nginx
#   ansible.builtin.dnf:
#     name: nginx
#     state: latest
#
# - name: Copy Expense Nginx Configuration
#   ansible.builtin.template:
#     src: expense.conf
#     dest: /etc/nginx/default.d/expense.conf
#
# - name: Import App Pre Requisites
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: app-pre-req
#
# - name: Start Nginx
#   ansible.builtin.systemd_service:
#     state: restarted
#     name: nginx
#     enabled: yes
# - name: Import NewRelic Nginx Setup
#   ansible.builtin.import_role:
#     name: newrelic
#     tasks_from: nginx

- name: Install Caddy
  ansible.builtin.get_url:
    url: https://caddyserver.com/api/download?os=linux&arch=amd64
    dest: /bin/caddy
    mode: '0755'

- name: Add App User
  ansible.builtin.user:
    name: "{{app_user}}"

- name: Import App Pre Requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: Copy Caddy configuration file
  ansible.builtin.template:
    src: Caddyfile
    dest: "{{app_loc}}/Caddyfile"

- name: Copy Caddy service file
  ansible.builtin.template:
    src: caddy.service
    dest: /etc/systemd/system/caddy.service

- name: Start Caddy Service
  ansible.builtin.systemd_service:
    name: caddy
    state: restarted
    enabled: yes
    daemon-reload: yes
