format_version: 10
pipelines:
  expense-frontend:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-3a51435:
        git: https://github.com/saiyadaz/expense-ansible2.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
       vault_token: AES:Gkr6fGBncKIt9QYs3Kz1Uw==:13xBUpMFlUoVXOuDFRKhoG0xh0AiM93JvP1kvqVjyUQ=
    stages:
      - Dev:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          allow_only_on_success: false
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash
                    run_if: passed
      - QA:
          fetch_materials: true
          environment_variables:
            env: qa
            approval:
            type: manual
          allow_only_on_success: false
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash
                    run_if: passed
      - stage:
          fetch_materials: true
          environment_variables:
            env: stage
          approval:
            type: manual
          allow_only_on_success: false
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash
                    run_if: passed
      - Prod:
          fetch_materials: true
          environment_variables:
            env: prod
          approval:
            type: manual
          allow_only_on_success: false
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash
                    run_if: passed

